import {reactive} from "vue";
export const store = reactive({
  user_name: null,
  password: '',
  backtestbackup:{
    "LSTM": {
      "advice": [
        "1. \"Given the negative Sharpe Ratio (-0.43), it's important to note that the risk-adjusted return for this stock portfolio is relatively low. This suggests that while there may be some short-term gains, investors might not be compensated adequately for the level of risk taken. Consider diversifying your portfolio or exploring other investment options with higher Sharpe Ratios.\"",
        "2. \"The small Alpha value (0.0059) indicates that the portfolio's excess return over the benchmark index is minimal. This means that any gains might be due to market fluctuations rather than skillful management. It would be advisable to re-evaluate the weightings or seek more actively managed funds for better performance.\"",
        "3. \"A significant negative Beta (-1.47e-05) implies that the stocks are less responsive to market movements, which could be a positive attribute in volatile times. However, it also suggests underperformance during bull markets. Investors should consider hedging strategies or rebalancing to protect against potential downturns.\""
      ],
      "alpha": 0.0059647694023706194,
      "beta": -0.000014722136311978026,
      "daily_cash": [
        [
          "2023-07-12",
          810
        ],
        [
          "2023-07-13",
          711.7323262581591
        ],
        [
          "2023-07-14",
          718.7455601329402
        ],
        [
          "2023-07-17",
          708.4337731308168
        ],
        [
          "2023-07-18",
          695.6517486763844
        ],
        [
          "2023-07-19",
          679.5193844184552
        ],
        [
          "2023-07-20",
          665.6144987358026
        ],
        [
          "2023-07-21",
          632.1593105158768
        ],
        [
          "2023-07-24",
          652.9030558739667
        ],
        [
          "2023-07-25",
          617.8944671787583
        ],
        [
          "2023-07-26",
          616.506754044316
        ],
        [
          "2023-07-27",
          595.3141080488114
        ],
        [
          "2023-07-28",
          554.446485719703
        ]
      ],
      "image_path": "images/portfolio_value_lstm.png",
      "return_rate": 0.3990331339895988,
      "sharpe_ratio": -0.43107705089665405
    },
    "XGBoost": {
      "advice": [
        "1. \"Based on the negative Sharpe Ratio (-0.456), it's important to note that this strategy might not outperform a risk-free investment. It suggests that for the level of risk taken, the returns generated are insufficient. Consider diversifying or exploring alternative strategies with higher risk-adjusted returns.\"",
        "2. \"The low Alpha (0.0034) indicates that the excess return generated by the portfolio compared to the benchmark is minimal. This could mean that the portfolio is not consistently beating the market. A reevaluation of weights and selection criteria for AAPL, MSFT, and AMZN might be necessary.\"",
        "3. \"The Beta of 0.0071 indicates a slight sensitivity to market movements. If the broader market experiences downturns, these stocks might experience a similar decline. It's advisable to hedge or limit exposure to protect against potential systemic risks.\""
      ],
      "alpha": 0.003476019272145086,
      "beta": 0.007155428749559587,
      "daily_cash": [
        [
          "2023-07-12",
          729
        ],
        [
          "2023-07-13",
          701.49695272819
        ],
        [
          "2023-07-14",
          671.1332739152961
        ],
        [
          "2023-07-17",
          657.6065309423825
        ],
        [
          "2023-07-18",
          667.3812247208695
        ],
        [
          "2023-07-19",
          660.7258020824644
        ],
        [
          "2023-07-20",
          695.0119173771159
        ],
        [
          "2023-07-21",
          710.0766306895077
        ],
        [
          "2023-07-24",
          697.917614045547
        ],
        [
          "2023-07-25",
          667.2589525051026
        ],
        [
          "2023-07-26",
          674.0507414462646
        ],
        [
          "2023-07-27",
          691.2221719839464
        ],
        [
          "2023-07-28",
          660.0162233566366
        ]
      ],
      "image_path": "images/portfolio_value_xgboost.png",
      "return_rate": 0.3281658257045251,
      "sharpe_ratio": -0.45647612220711464
    },
    "best_model": "LSTM",
    "lightGBM": {
      "advice": [
        "1. \"Based on the backtesting results, the stock portfolio of AAPL, MSFT, and AMZN has a relatively low Sharpe Ratio (-0.52), indicating that the risk-adjusted returns are negative. This suggests that the strategy may not be optimal for risk-averse investors. Consider diversifying your portfolio to mitigate potential losses.\"",
        "2. \"The Alpha value of 0.0021 indicates a slight outperformance compared to the benchmark, but it's minimal. It's advisable to monitor these stocks closely and consider alternative investments with higher alpha to maximize returns.\"",
        "3. \"A beta of 0.014 suggests a low correlation with the market, which could offer some stability in a volatile market. However, since the beta is so close to zero, it might not provide significant protection during downturns. Be prepared for potential market fluctuations.\""
      ],
      "alpha": 0.002114361707514676,
      "beta": 0.014084214525428778,
      "daily_cash": [
        [
          "2023-07-12",
          729
        ],
        [
          "2023-07-13",
          721.5781024353445
        ],
        [
          "2023-07-14",
          693.2241195506609
        ],
        [
          "2023-07-17",
          681.9462989705203
        ],
        [
          "2023-07-18",
          649.1004051917421
        ],
        [
          "2023-07-19",
          640.619299064765
        ],
        [
          "2023-07-20",
          676.8335498580764
        ],
        [
          "2023-07-21",
          690.1624072017939
        ],
        [
          "2023-07-24",
          701.576994069506
        ],
        [
          "2023-07-25",
          671.3893007977157
        ],
        [
          "2023-07-26",
          682.4511859985611
        ],
        [
          "2023-07-27",
          690.1077838814816
        ],
        [
          "2023-07-28",
          658.9018352541718
        ]
      ],
      "image_path": "images/portfolio_value_lightgbm.png",
      "return_rate": 0.21672701545803646,
      "sharpe_ratio": -0.5217101884290529
    }
  },
  stockList: ['AAPL', 'MSFT', 'AMZN', 'GOOGL', 'GOOG', 'FB', 'BRK-A', 'BRK-B', 'JNJ', 'TSLA',
    'V', 'WMT', 'JPM', 'MA', 'PG', 'NVDA', 'HD', 'DIS', 'UNH', 'PYPL', 'BAC', 'INTC',
    'CMCSA', 'VZ', 'NFLX', 'PFE', 'ADBE', 'T', 'PEP', 'CRM', 'ABT', 'CSCO', 'ABBV',
    'XOM', 'AVGO', 'KO', 'CMG', 'AMD', 'DUK', 'QCOM', 'TMO', 'COST', 'LLY', 'NEE',
    'MRK', 'MDT', 'TMUS', 'ORCL', 'ACN', 'NKE', 'CL'],
  stockMap:{ 'AAPL': 'Apple Inc.', 'MSFT': 'Microsoft Corporation', 'AMZN': 'Amazon.com Inc.', 'GOOGL': 'Alphabet Inc.', 'GOOG': 'Alphabet Inc.', 'FB': 'Meta Platforms Inc.', 'BRK-A': 'Berkshire Hathaway Inc.', 'BRK-B': 'Berkshire Hathaway Inc.', 'JNJ': 'Johnson & Johnson', 'TSLA': 'Tesla Inc.', 'V': 'Visa Inc.', 'WMT': 'Walmart Inc.', 'JPM': 'JPMorgan Chase & Co.', 'MA': 'Mastercard Inc.', 'PG': 'Procter & Gamble Company', 'NVDA': 'NVIDIA Corporation', 'HD': 'The Home Depot Inc.', 'DIS': 'The Walt Disney Company', 'UNH': 'UnitedHealth Group Inc.', 'PYPL': 'PayPal Holdings Inc.', 'BAC': 'Bank of America Corporation', 'INTC': 'Intel Corporation', 'CMCSA': 'Comcast Corporation', 'VZ': 'Verizon Communications Inc.', 'NFLX': 'Netflix Inc.', 'PFE': 'Pfizer Inc.', 'ADBE': 'Adobe Inc.', 'T': 'AT&T Inc.', 'PEP': 'PepsiCo Inc.', 'CRM': 'Salesforce.com Inc.', 'ABT': 'Abbott Laboratories', 'CSCO': 'Cisco Systems Inc.', 'ABBV': 'AbbVie Inc.', 'XOM': 'Exxon Mobil Corporation', 'AVGO': 'Broadcom Inc.', 'KO': 'The Coca-Cola Company', 'CMG': 'Chipotle Mexican Grill Inc.', 'AMD': 'Advanced Micro Devices Inc.', 'DUK': 'Duke Energy Corporation', 'QCOM': 'QUALCOMM Incorporated', 'TMO': 'Thermo Fisher Scientific Inc.', 'COST': 'Costco Wholesale Corporation', 'LLY': 'Eli Lilly and Company', 'NEE': 'NextEra Energy Inc.', 'MRK': 'Merck & Co. Inc.', 'MDT': 'Medtronic plc', 'TMUS': 'T-Mobile US Inc.', 'ORCL': 'Oracle Corporation', 'ACN': 'Accenture plc', 'NKE': 'NIKE Inc.', 'CL': 'Colgate-Palmolive Company' }
})
